insert into person (address, first_name, gender, last_name, enabled) values ('093 Oneill Alley', 'Kaye', 'Female', 'Wasbrough', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Ridgeway Place', 'Koressa', 'Female', 'Gadman', false);
insert into person (address, first_name, gender, last_name, enabled) values ('704 Cambridge Plaza', 'Calhoun', 'Male', 'Staveley', false);
insert into person (address, first_name, gender, last_name, enabled) values ('22 Melvin Court', 'Mable', 'Female', 'Navarro', false);
insert into person (address, first_name, gender, last_name, enabled) values ('86619 Montana Trail', 'Rebbecca', 'Female', 'Bastock', true);
insert into person (address, first_name, gender, last_name, enabled) values ('820 Hoard Court', 'Archibald', 'Male', 'Chaim', true);
insert into person (address, first_name, gender, last_name, enabled) values ('42 Kedzie Pass', 'Westley', 'Male', 'Rosier', false);
insert into person (address, first_name, gender, last_name, enabled) values ('1 Dayton Center', 'Donalt', 'Male', 'Glasper', false);
insert into person (address, first_name, gender, last_name, enabled) values ('555 Wayridge Junction', 'Gearard', 'Male', 'Speller', true);
insert into person (address, first_name, gender, last_name, enabled) values ('5 Milwaukee Plaza', 'Abraham', 'Male', 'Maha', false);
insert into person (address, first_name, gender, last_name, enabled) values ('3935 Blue Bill Park Junction', 'Romonda', 'Female', 'Havill', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Heffernan Avenue', 'Cynthie', 'Female', 'Gaymar', false);
insert into person (address, first_name, gender, last_name, enabled) values ('50680 American Ash Center', 'Dannel', 'Male', 'Batisse', false);
insert into person (address, first_name, gender, last_name, enabled) values ('757 Carpenter Plaza', 'Neel', 'Male', 'Thirkettle', true);
insert into person (address, first_name, gender, last_name, enabled) values ('96 Burrows Center', 'Aldridge', 'Male', 'Luigi', true);
insert into person (address, first_name, gender, last_name, enabled) values ('7593 Aberg Street', 'Margi', 'Female', 'Ellaway', true);
insert into person (address, first_name, gender, last_name, enabled) values ('86770 Truax Center', 'Bidget', 'Female', 'Cuppitt', true);
insert into person (address, first_name, gender, last_name, enabled) values ('542 Cascade Plaza', 'Sheffie', 'Male', 'Matthews', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Ridge Oak Junction', 'Cairistiona', 'Female', 'Rasher', true);
insert into person (address, first_name, gender, last_name, enabled) values ('43218 Birchwood Alley', 'Birdie', 'Female', 'Dennison', true);
insert into person (address, first_name, gender, last_name, enabled) values ('79 Pepper Wood Hill', 'Mariette', 'Female', 'McCrann', true);
insert into person (address, first_name, gender, last_name, enabled) values ('3556 Linden Trail', 'Veriee', 'Female', 'Konzel', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6728 Carpenter Plaza', 'Rafe', 'Male', 'Castillon', true);
insert into person (address, first_name, gender, last_name, enabled) values ('8 Pennsylvania Terrace', 'Eloisa', 'Female', 'McReidy', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6914 Beilfuss Trail', 'Viole', 'Female', 'Mackieson', true);
insert into person (address, first_name, gender, last_name, enabled) values ('1779 Ronald Regan Place', 'Johny', 'Male', 'Grzegorczyk', false);
insert into person (address, first_name, gender, last_name, enabled) values ('96696 Rigney Lane', 'Randell', 'Male', 'Noli', false);
insert into person (address, first_name, gender, last_name, enabled) values ('91 Claremont Hill', 'Lowe', 'Male', 'Jacobovitch', false);
insert into person (address, first_name, gender, last_name, enabled) values ('94 Goodland Street', 'Osmond', 'Male', 'McFeate', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Lakewood Alley', 'Georges', 'Male', 'Skeeles', true);
insert into person (address, first_name, gender, last_name, enabled) values ('9947 Dennis Park', 'Arleta', 'Female', 'Land', false);
insert into person (address, first_name, gender, last_name, enabled) values ('5 Miller Center', 'Hall', 'Male', 'Leipelt', true);
insert into person (address, first_name, gender, last_name, enabled) values ('38 Huxley Alley', 'Juline', 'Female', 'Quinet', true);
insert into person (address, first_name, gender, last_name, enabled) values ('33 8th Street', 'Minda', 'Female', 'Dixcey', true);
insert into person (address, first_name, gender, last_name, enabled) values ('9154 Northland Junction', 'Garreth', 'Male', 'Eatttok', false);
insert into person (address, first_name, gender, last_name, enabled) values ('59525 Dexter Circle', 'Keen', 'Male', 'Rogan', true);
insert into person (address, first_name, gender, last_name, enabled) values ('908 Truax Crossing', 'Dido', 'Female', 'Fitchew', false);
insert into person (address, first_name, gender, last_name, enabled) values ('797 Annamark Terrace', 'Alvan', 'Male', 'Slimmon', false);
insert into person (address, first_name, gender, last_name, enabled) values ('604 Oxford Crossing', 'Nolly', 'Male', 'Fick', false);
insert into person (address, first_name, gender, last_name, enabled) values ('86 Lighthouse Bay Terrace', 'Brice', 'Male', 'Wellings', true);
insert into person (address, first_name, gender, last_name, enabled) values ('80934 Barby Drive', 'Rheta', 'Female', 'Cruce', true);
insert into person (address, first_name, gender, last_name, enabled) values ('38211 Grim Circle', 'Dee dee', 'Female', 'Middell', false);
insert into person (address, first_name, gender, last_name, enabled) values ('9732 Miller Circle', 'Tarrah', 'Female', 'Worsnup', false);
insert into person (address, first_name, gender, last_name, enabled) values ('75 Ridgeview Parkway', 'Jeramie', 'Male', 'Counsell', true);
insert into person (address, first_name, gender, last_name, enabled) values ('17270 Mcguire Terrace', 'Borden', 'Male', 'Lazonby', false);
insert into person (address, first_name, gender, last_name, enabled) values ('10 Forest Run Circle', 'Pippy', 'Female', 'Torrans', false);
insert into person (address, first_name, gender, last_name, enabled) values ('737 Golf Circle', 'Cleo', 'Female', 'Jirka', false);
insert into person (address, first_name, gender, last_name, enabled) values ('55 Vernon Lane', 'Tate', 'Female', 'Jedryka', true);
insert into person (address, first_name, gender, last_name, enabled) values ('0 Jay Plaza', 'Decca', 'Male', 'Bligh', false);
insert into person (address, first_name, gender, last_name, enabled) values ('55190 Cherokee Avenue', 'Reid', 'Male', 'Lafford', true);
insert into person (address, first_name, gender, last_name, enabled) values ('1 Portage Hill', 'Kilian', 'Male', 'Lethlay', true);
insert into person (address, first_name, gender, last_name, enabled) values ('92 Farragut Pass', 'Dannel', 'Male', 'Mease', true);
insert into person (address, first_name, gender, last_name, enabled) values ('74 Utah Way', 'Rennie', 'Female', 'Moorwood', false);
insert into person (address, first_name, gender, last_name, enabled) values ('331 Acker Drive', 'Eugenie', 'Female', 'Bengochea', true);
insert into person (address, first_name, gender, last_name, enabled) values ('57 Forest Lane', 'Tabitha', 'Female', 'Keel', false);
insert into person (address, first_name, gender, last_name, enabled) values ('960 Talmadge Place', 'Katherina', 'Female', 'Ehrat', false);